pipeline:

  build:
    image: quay.io/ukhomeofficedigital/drone-docker
    commands:
      - docker build -t cop-data-api:$${DRONE_COMMIT_SHA} .
    when:
      event: push

  unit_tests:
    image: quay.io/ukhomeofficedigital/drone-docker
    commands:
      - docker run -t cop-data-api:$${DRONE_COMMIT_SHA} sh -c "npm test"
    when:
      event: push

  lint_checks:
    image: quay.io/ukhomeofficedigital/drone-docker
    commands:
      - docker run -t cop-data-api:$${DRONE_COMMIT_SHA} sh -c "npm run lint -- app/"
    when:
      event: push

  image_to_quay:
    image: quay.io/ukhomeofficedigital/drone-docker
    secrets:
    - source: DEV_QUAY_USERNAME
      target: DOCKER_USERNAME
    - source: DEV_QUAY_PASSWORD
      target: DOCKER_PASSWORD
    registry: quay.io
    repo: quay.io/ukhomeofficedigital/cop-data-api
    tags: ${DRONE_COMMIT_SHA}
    when:
      branch: master
      event: push

  deploy_to_dev:
    image: quay.io/ukhomeofficedigital/kd
    secrets:
      - DEV_NGINX_IMAGE
      - DEV_NGINX_TAG
      - DEV_KUBE_SERVER
      - DEV_KUBE_TOKEN
      - DEV_KEYCLOAK_URL
      - DEV_KEYCLOAK_REALM
      - DEV_KEYCLOAK_PROTOCOL
      - DEV_DB_COP_PROTOCOL
      - DEV_DB_COP_PORT
      - DEV_DB_COP_HOSTNAME
      - DEV_DB_COP_OPTIONS
      - DEV_DB_COP_OPERATION_DBNAME
      - DEV_DB_COP_OPERATION_SCHEMA
      - DEV_DB_COP_OPERATION_AUTHENTICATOR_USERNAME
      - DEV_DB_COP_OPERATION_AUTHENTICATOR_PASSWORD
      - DEV_API_COP_NAME
      - DEV_API_COP_URL
      - DEV_API_COP_IMAGE
      - DEV_API_COP_PROTOCOL
      - DEV_API_COP_KEYCLOAK_CLIENT_ID
      - DEV_API_COP_KUBE_NAMESPACE
      - DEV_API_COP_LOG_LEVEL
      - DEV_API_COP_PORT
    commands:
      - export NGINX_IMAGE=$${DEV_NGINX_IMAGE}
      - export NGINX_TAG=$${DEV_NGINX_TAG}
      - export KUBE_SERVER=$${DEV_KUBE_SERVER}
      - export KUBE_TOKEN=$${DEV_KUBE_TOKEN}
      - export KUBE_NAMESPACE=$${DEV_API_COP_KUBE_NAMESPACE}
      - export KEYCLOAK_URL=$${DEV_KEYCLOAK_URL}
      - export KEYCLOAK_REALM=$${DEV_KEYCLOAK_REALM}
      - export KEYCLOAK_PROTOCOL=$${DEV_KEYCLOAK_PROTOCOL}
      - export DB_COP_PROTOCOL=$${DEV_DB_COP_PROTOCOL}
      - export DB_COP_PORT=$${DEV_DB_COP_PORT}
      - export DB_COP_HOSTNAME=$${DEV_DB_COP_HOSTNAME}
      - export DB_COP_OPTIONS=$${DEV_DB_COP_OPTIONS}
      - export DB_COP_OPERATION_DBNAME=$${DEV_DB_COP_OPERATION_DBNAME}
      - export DB_COP_OPERATION_SCHEMA=$${DEV_DB_COP_OPERATION_SCHEMA}
      - export DB_COP_OPERATION_AUTHENTICATOR_USERNAME=$${DEV_DB_COP_OPERATION_AUTHENTICATOR_USERNAME}
      - export DB_COP_OPERATION_AUTHENTICATOR_PASSWORD=$${DEV_DB_COP_OPERATION_AUTHENTICATOR_PASSWORD}
      - export API_COP_NAME=$${DEV_API_COP_NAME}
      - export API_COP_URL=$${DEV_API_COP_URL}
      - export API_COP_IMAGE=$${DEV_API_COP_IMAGE}
      - export API_COP_PROTOCOL=$${DEV_API_COP_PROTOCOL}
      - export API_COP_KEYCLOAK_CLIENT_ID=$${DEV_API_COP_KEYCLOAK_CLIENT_ID}
      - export API_COP_KUBE_NAMESPACE=$${DEV_API_COP_KUBE_NAMESPACE}
      - export API_COP_LOG_LEVEL=$${DEV_API_COP_LOG_LEVEL}
      - export API_COP_PORT=$${DEV_API_COP_PORT}
      - export API_COP_TAG=$${DRONE_COMMIT_SHA}
      - kd --insecure-skip-tls-verify -f kube/secret.yml -f kube/deployment.yml -f kube/service.yml -f kube/ingress.yml -f kube/network-policy.yml
    when:
      branch: master
      event: push

  deploy_to_staging:
    image: quay.io/ukhomeofficedigital/kd
    secrets:
      - STAGING_NGINX_IMAGE
      - STAGING_NGINX_TAG
      - STAGING_KUBE_SERVER
      - STAGING_KUBE_TOKEN
      - STAGING_KEYCLOAK_URL
      - STAGING_KEYCLOAK_REALM
      - STAGING_KEYCLOAK_PROTOCOL
      - STAGING_DB_COP_PROTOCOL
      - STAGING_DB_COP_PORT
      - STAGING_DB_COP_HOSTNAME
      - STAGING_DB_COP_OPTIONS
      - STAGING_DB_COP_OPERATION_DBNAME
      - STAGING_DB_COP_OPERATION_SCHEMA
      - STAGING_DB_COP_OPERATION_AUTHENTICATOR_USERNAME
      - STAGING_DB_COP_OPERATION_AUTHENTICATOR_PASSWORD
      - STAGING_API_COP_NAME
      - STAGING_API_COP_URL
      - STAGING_API_COP_IMAGE
      - STAGING_API_COP_PROTOCOL
      - STAGING_API_COP_KEYCLOAK_CLIENT_ID
      - STAGING_API_COP_KUBE_NAMESPACE
      - STAGING_API_COP_LOG_LEVEL
      - STAGING_API_COP_PORT
    commands:
      - export NGINX_IMAGE=$${STAGING_NGINX_IMAGE}
      - export NGINX_TAG=$${STAGING_NGINX_TAG}
      - export KUBE_SERVER=$${STAGING_KUBE_SERVER}
      - export KUBE_TOKEN=$${STAGING_KUBE_TOKEN}
      - export KUBE_NAMESPACE=$${STAGING_API_COP_KUBE_NAMESPACE}
      - export KEYCLOAK_URL=$${STAGING_KEYCLOAK_URL}
      - export KEYCLOAK_REALM=$${STAGING_KEYCLOAK_REALM}
      - export KEYCLOAK_PROTOCOL=$${STAGING_KEYCLOAK_PROTOCOL}
      - export DB_COP_PROTOCOL=$${STAGING_DB_COP_PROTOCOL}
      - export DB_COP_PORT=$${STAGING_DB_COP_PORT}
      - export DB_COP_HOSTNAME=$${STAGING_DB_COP_HOSTNAME}
      - export DB_COP_OPTIONS=$${STAGING_DB_COP_OPTIONS}
      - export DB_COP_OPERATION_DBNAME=$${STAGING_DB_COP_OPERATION_DBNAME}
      - export DB_COP_OPERATION_SCHEMA=$${STAGING_DB_COP_OPERATION_SCHEMA}
      - export DB_COP_OPERATION_AUTHENTICATOR_USERNAME=$${STAGING_DB_COP_OPERATION_AUTHENTICATOR_USERNAME}
      - export DB_COP_OPERATION_AUTHENTICATOR_PASSWORD=$${STAGING_DB_COP_OPERATION_AUTHENTICATOR_PASSWORD}
      - export API_COP_NAME=$${STAGING_API_COP_NAME}
      - export API_COP_URL=$${STAGING_API_COP_URL}
      - export API_COP_IMAGE=$${STAGING_API_COP_IMAGE}
      - export API_COP_PROTOCOL=$${STAGING_API_COP_PROTOCOL}
      - export API_COP_KEYCLOAK_CLIENT_ID=$${STAGING_API_COP_KEYCLOAK_CLIENT_ID}
      - export API_COP_KUBE_NAMESPACE=$${STAGING_API_COP_KUBE_NAMESPACE}
      - export API_COP_LOG_LEVEL=$${STAGING_API_COP_LOG_LEVEL}
      - export API_COP_PORT=$${STAGING_API_COP_PORT}
      - export API_COP_TAG=$${DRONE_COMMIT_SHA}
      - kd --insecure-skip-tls-verify -f kube/deployment.yml -f kube/service.yml -f kube/ingress.yml -f kube/network-policy.yml
    when:
      event: deployment
      environment: staging
      branch: master

  deploy_to_production:
    image: quay.io/ukhomeofficedigital/kd
    secrets:
      - PRODUCTION_NGINX_IMAGE
      - PRODUCTION_NGINX_TAG
      - PRODUCTION_KUBE_SERVER
      - PRODUCTION_KUBE_TOKEN
      - PRODUCTION_KEYCLOAK_URL
      - PRODUCTION_KEYCLOAK_REALM
      - PRODUCTION_KEYCLOAK_PROTOCOL
      - PRODUCTION_DB_COP_PROTOCOL
      - PRODUCTION_DB_COP_PORT
      - PRODUCTION_DB_COP_HOSTNAME
      - PRODUCTION_DB_COP_OPTIONS
      - PRODUCTION_DB_COP_OPERATION_DBNAME
      - PRODUCTION_DB_COP_OPERATION_SCHEMA
      - PRODUCTION_DB_COP_OPERATION_AUTHENTICATOR_USERNAME
      - PRODUCTION_DB_COP_OPERATION_AUTHENTICATOR_PASSWORD
      - PRODUCTION_API_COP_NAME
      - PRODUCTION_API_COP_URL
      - PRODUCTION_API_COP_IMAGE
      - PRODUCTION_API_COP_PROTOCOL
      - PRODUCTION_API_COP_KEYCLOAK_CLIENT_ID
      - PRODUCTION_API_COP_KUBE_NAMESPACE
      - PRODUCTION_API_COP_LOG_LEVEL
      - PRODUCTION_API_COP_PORT
    commands:
      - export NGINX_IMAGE=$${PRODUCTION_NGINX_IMAGE}
      - export NGINX_TAG=$${PRODUCTION_NGINX_TAG}
      - export KUBE_SERVER=$${PRODUCTION_KUBE_SERVER}
      - export KUBE_TOKEN=$${PRODUCTION_KUBE_TOKEN}
      - export KUBE_NAMESPACE=$${PRODUCTION_API_COP_KUBE_NAMESPACE}
      - export KEYCLOAK_URL=$${PRODUCTION_KEYCLOAK_URL}
      - export KEYCLOAK_REALM=$${PRODUCTION_KEYCLOAK_REALM}
      - export KEYCLOAK_PROTOCOL=$${PRODUCTION_KEYCLOAK_PROTOCOL}
      - export DB_COP_PROTOCOL=$${PRODUCTION_DB_COP_PROTOCOL}
      - export DB_COP_PORT=$${PRODUCTION_DB_COP_PORT}
      - export DB_COP_HOSTNAME=$${PRODUCTION_DB_COP_HOSTNAME}
      - export DB_COP_OPTIONS=$${PRODUCTION_DB_COP_OPTIONS}
      - export DB_COP_OPERATION_DBNAME=$${PRODUCTION_DB_COP_OPERATION_DBNAME}
      - export DB_COP_OPERATION_SCHEMA=$${PRODUCTION_DB_COP_OPERATION_SCHEMA}
      - export DB_COP_OPERATION_AUTHENTICATOR_USERNAME=$${PRODUCTION_DB_COP_OPERATION_AUTHENTICATOR_USERNAME}
      - export DB_COP_OPERATION_AUTHENTICATOR_PASSWORD=$${PRODUCTION_DB_COP_OPERATION_AUTHENTICATOR_PASSWORD}
      - export API_COP_NAME=$${PRODUCTION_API_COP_NAME}
      - export API_COP_URL=$${PRODUCTION_API_COP_URL}
      - export API_COP_IMAGE=$${PRODUCTION_API_COP_IMAGE}
      - export API_COP_PROTOCOL=$${PRODUCTION_API_COP_PROTOCOL}
      - export API_COP_KEYCLOAK_CLIENT_ID=$${PRODUCTION_API_COP_KEYCLOAK_CLIENT_ID}
      - export API_COP_KUBE_NAMESPACE=$${PRODUCTION_API_COP_KUBE_NAMESPACE}
      - export API_COP_LOG_LEVEL=$${PRODUCTION_API_COP_LOG_LEVEL}
      - export API_COP_PORT=$${PRODUCTION_API_COP_PORT}
      - export API_COP_TAG=$${DRONE_COMMIT_SHA}
      - kd --insecure-skip-tls-verify -f kube/deployment.yml -f kube/service.yml -f kube/ingress.yml -f kube/network-policy.yml
    when:
      event: deployment
      environment: production
      branch: master

  notify:
    image: plugins/slack
    secrets: [ SLACK_WEBHOOK ]
    channel: cop-deployments
    username: Drone Build Watcher
    template: >
      {{#build.deployTo}}
        *{{repo.name}} - Build {{build.number}} - {{uppercasefirst build.deployTo}} - {{uppercase build.status}}*
        {{build.link}}
      {{else}}
        *{{repo.name}} - Build {{build.number}} - Development - {{uppercase build.status}}*
        {{build.link}}
      {{/build.deployTo}}
    when:
      branch: master
      event: [ push, deployment ]
      status: [ success, failure ]
