pipeline:

  build:
    image: quay.io/ukhomeofficedigital/drone-docker
    commands:
      - docker build -t cop-data-api:$${DRONE_COMMIT_SHA} .
    when:
      event: push

  unit_tests:
    image: quay.io/ukhomeofficedigital/drone-docker
    commands:
      - docker run -t cop-data-api:$${DRONE_COMMIT_SHA} sh -c "npm test"
    when:
      event: push

  image_to_quay:
    image: quay.io/ukhomeofficedigital/drone-docker
    secrets:
      - DOCKER_USERNAME
      - DOCKER_PASSWORD
    registry: quay.io
    repo: quay.io/ukhomeofficedigital/cop-data-api
    tags:
      - ${DRONE_BUILD_NUMBER}
      - ${DRONE_COMMIT_SHA}
      - latest
    when:
      branch: master
      event: push

  deploy_to_dev:
    image: quay.io/ukhomeofficedigital/kd
    secrets:
      - DEV_HOSTNAME
      - DEV_KUBE_NAMESPACE
      - DEV_KUBE_SERVER
      - DEV_KUBE_TOKEN
      - DEV_LOG_LEVEL
      - DEV_DB_CONNECTION_STRING
    commands:
      - export HOSTNAME=$${DEV_HOSTNAME}
      - export KUBE_NAMESPACE=$${DEV_KUBE_NAMESPACE}
      - export KUBE_SERVER=$${DEV_KUBE_SERVER}
      - export KUBE_TOKEN=$${DEV_KUBE_TOKEN}
      - export LOG_LEVEL=$${DEV_LOG_LEVEL}
      - export DB_CONNECTION_STRING=$${DEV_DB_CONNECTION_STRING}
      - kd --insecure-skip-tls-verify -f kube/deployment.yml -f kube/service.yml -f kube/ingress.yml -f kube/network-policy.yml
    when:
      branch: master
      event: push

  deploy_to_staging:
    image: quay.io/ukhomeofficedigital/kd
    secrets:
      - STAGING_HOSTNAME
      - STAGING_KUBE_NAMESPACE
      - STAGING_KUBE_SERVER
      - STAGING_KUBE_TOKEN
      - STAGING_LOG_LEVEL
      - STAGING_DB_CONNECTION_STRING
    commands:
      - export HOSTNAME=$${STAGING_HOSTNAME}
      - export KUBE_NAMESPACE=$${STAGING_KUBE_NAMESPACE}
      - export KUBE_SERVER=$${STAGING_KUBE_SERVER}
      - export KUBE_TOKEN=$${STAGING_KUBE_TOKEN}
      - export LOG_LEVEL=$${STAGING_LOG_LEVEL}
      - export DB_CONNECTION_STRING=$${STAGING_DB_CONNECTION_STRING}
      - kd --insecure-skip-tls-verify -f kube/deployment.yml -f kube/service.yml -f kube/ingress.yml -f kube/network-policy.yml
    when:
      event: deployment
      environment: staging
      branch: master

  deploy_to_prod:
    image: quay.io/ukhomeofficedigital/kd
    secrets:
      - PROD_HOSTNAME
      - PROD_KUBE_NAMESPACE
      - PROD_KUBE_SERVER
      - PROD_KUBE_TOKEN
      - PROD_LOG_LEVEL
      - PROD_DB_CONNECTION_STRING
    commands:
      - export HOSTNAME=$${PROD_HOSTNAME}
      - export KUBE_NAMESPACE=$${PROD_KUBE_NAMESPACE}
      - export KUBE_SERVER=$${PROD_KUBE_SERVER}
      - export KUBE_TOKEN=$${PROD_KUBE_TOKEN}
      - export LOG_LEVEL=$${PROD_LOG_LEVEL}
      - export DB_CONNECTION_STRING=$${PROD_DB_CONNECTION_STRING}
      - kd --insecure-skip-tls-verify -f kube/deployment.yml -f kube/service.yml -f kube/ingress.yml -f kube/network-policy.yml
    when:
      event: deployment
      environment: production
      branch: master
