pipeline:

  build:
    image: quay.io/ukhomeofficedigital/drone-docker
    commands:
      - docker build -t cop-data-api:$${DRONE_COMMIT_SHA} .
    when:
      event: push

  unit_tests:
    image: quay.io/ukhomeofficedigital/drone-docker
    commands:
      - docker run -t cop-data-api:$${DRONE_COMMIT_SHA} sh -c "npm test"
    when:
      event: push

  lint_checks:
    image: quay.io/ukhomeofficedigital/drone-docker
    commands:
      - docker run -t cop-data-api:$${DRONE_COMMIT_SHA} sh -c "npm run lint -- app/"
    when:
      event: push

  image_to_quay:
    image: quay.io/ukhomeofficedigital/drone-docker
    secrets:
    - source: DEV_QUAY_USERNAME
      target: DOCKER_USERNAME
    - source: DEV_QUAY_PASSWORD
      target: DOCKER_PASSWORD
    registry: quay.io
    repo: quay.io/ukhomeofficedigital/cop-data-api
    tags: ${DRONE_COMMIT_SHA}
    when:
      branch: master
      event: push

  deploy_to_dev:
    image: quay.io/ukhomeofficedigital/kd
    secrets:
      - DEV_NGINX_IMAGE
      - DEV_NGINX_TAG
      - DEV_KUBE_SERVER
      - DEV_KUBE_TOKEN
      - DEV_KEYCLOAK_URL
      - DEV_KEYCLOAK_REALM
      - DEV_KEYCLOAK_PROTOCOL
      - DEV_DB_COP_PROTOCOL
      - DEV_DB_COP_PORT
      - DEV_DB_COP_HOSTNAME
      - DEV_DB_COP_OPTIONS
      - DEV_DB_COP_OPERATION_DBNAME
      - DEV_DB_COP_OPERATION_SCHEMA
      - DEV_DB_COP_OPERATION_AUTHENTICATOR_USERNAME
      - DEV_DB_COP_OPERATION_AUTHENTICATOR_PASSWORD
      - DEV_API_COP_NAME
      - DEV_API_COP_URL
      - DEV_API_COP_IMAGE
      - DEV_API_COP_PROTOCOL
      - DEV_API_COP_KEYCLOAK_CLIENT_ID
      - DEV_API_COP_KUBE_NAMESPACE
      - DEV_API_COP_LOG_LEVEL
      - DEV_API_COP_PORT
    commands:
      - export NGINX_IMAGE=$${DEV_NGINX_IMAGE}
      - export NGINX_TAG=$${DEV_NGINX_TAG}
      - export KUBE_SERVER=$${DEV_KUBE_SERVER}
      - export KUBE_TOKEN=$${DEV_KUBE_TOKEN}
      - export KUBE_NAMESPACE=$${DEV_API_COP_KUBE_NAMESPACE}
      - export KEYCLOAK_URL=$${DEV_KEYCLOAK_URL}
      - export KEYCLOAK_REALM=$${DEV_KEYCLOAK_REALM}
      - export KEYCLOAK_PROTOCOL=$${DEV_KEYCLOAK_PROTOCOL}
      - export DB_COP_PROTOCOL=$${DEV_DB_COP_PROTOCOL}
      - export DB_COP_PORT=$${DEV_DB_COP_PORT}
      - export DB_COP_HOSTNAME=$${DEV_DB_COP_HOSTNAME}
      - export DB_COP_OPTIONS=$${DEV_DB_COP_OPTIONS}
      - export DB_COP_OPERATION_DBNAME=$${DEV_DB_COP_OPERATION_DBNAME}
      - export DB_COP_OPERATION_SCHEMA=$${DEV_DB_COP_OPERATION_SCHEMA}
      - export DB_COP_OPERATION_AUTHENTICATOR_USERNAME=$${DEV_DB_COP_OPERATION_AUTHENTICATOR_USERNAME}
      - export DB_COP_OPERATION_AUTHENTICATOR_PASSWORD=$${DEV_DB_COP_OPERATION_AUTHENTICATOR_PASSWORD}
      - export API_COP_NAME=$${DEV_API_COP_NAME}
      - export API_COP_URL=$${DEV_API_COP_URL}
      - export API_COP_IMAGE=$${DEV_API_COP_IMAGE}
      - export API_COP_PROTOCOL=$${DEV_API_COP_PROTOCOL}
      - export API_COP_KEYCLOAK_CLIENT_ID=$${DEV_API_COP_KEYCLOAK_CLIENT_ID}
      - export API_COP_KUBE_NAMESPACE=$${DEV_API_COP_KUBE_NAMESPACE}
      - export API_COP_LOG_LEVEL=$${DEV_API_COP_LOG_LEVEL}
      - export API_COP_PORT=$${DEV_API_COP_PORT}
      - export API_COP_TAG=$${DRONE_COMMIT_SHA}
      - kd --insecure-skip-tls-verify -f kube/deployment.yml -f kube/service.yml -f kube/ingress.yml -f kube/network-policy.yml
    when:
      branch: master
      event: push

  deploy_to_staging:
    image: quay.io/ukhomeofficedigital/kd
    secrets:
      - STAGING_HOSTNAME
      - STAGING_COP_DATA_API_KUBE_NAMESPACE
      - STAGING_KUBE_SERVER
      - STAGING_KUBE_TOKEN
      - STAGING_KEYCLOAK_URL
      - STAGING_KEYCLOAK_PROTOCOL
      - STAGING_KEYCLOAK_REALM
      - STAGING_COP_DATA_API_KEYCLOAK_CLIENT_ID
      - STAGING_COP_DATA_API_LOG_LEVEL
      - STAGING_COP_DATA_API_DB_CONNECTION_STRING
      - STAGING_DB_DATA_COP_OPERATION_SCHEMA
      - STAGING_COP_DATA_API_IMAGE_REPO
      - STAGING_COP_DATA_API_PORT
      - STAGING_NGINX_IMAGE_PROXY_REPO
      - STAGING_NGINX_IMAGE_PROXY_TAG
    commands:
      - export HOSTNAME=$${STAGING_HOSTNAME}
      - export COP_DATA_API_KUBE_NAMESPACE=$${STAGING_COP_DATA_API_KUBE_NAMESPACE}
      - export KUBE_SERVER=$${STAGING_KUBE_SERVER}
      - export KUBE_TOKEN=$${STAGING_KUBE_TOKEN}
      - export KEYCLOAK_URL=$${STAGING_KEYCLOAK_URL}
      - export KEYCLOAK_PROTOCOL=$${STAGING_KEYCLOAK_PROTOCOL}
      - export KEYCLOAK_REALM=$${STAGING_KEYCLOAK_REALM}
      - export COP_DATA_API_KEYCLOAK_CLIENT_ID=$${STAGING_COP_DATA_API_KEYCLOAK_CLIENT_ID}
      - export COP_DATA_API_LOG_LEVEL=$${STAGING_COP_DATA_API_LOG_LEVEL}
      - export COP_DATA_API_DB_CONNECTION_STRING=$${STAGING_COP_DATA_API_DB_CONNECTION_STRING}
      - export COP_DATA_API_PORT=$${STAGING_COP_DATA_API_PORT}
      - export DB_DATA_COP_OPERATION_SCHEMA=$${STAGING_DB_DATA_COP_OPERATION_SCHEMA}
      - export COP_DATA_API_IMAGE_REPO=$${STAGING_COP_DATA_API_IMAGE_REPO}
      - export NGINX_PROXY_IMAGE_REPO=$${STAGING_NGINX_PROXY_IMAGE_REPO}
      - export NGINX_PROXY_IMAGE_TAG=$${STAGING_NGINX_PROXY_IMAGE_TAG}
      - kd --insecure-skip-tls-verify -f kube/deployment.yml -f kube/service.yml -f kube/ingress.yml -f kube/network-policy.yml
    when:
      event: deployment
      environment: staging
      branch: master

  deploy_to_production:
    image: quay.io/ukhomeofficedigital/kd
    secrets:
      - PRODUCTION_HOSTNAME
      - PRODUCTION_COP_DATA_API_KUBE_NAMESPACE
      - PRODUCTION_KUBE_SERVER
      - PRODUCTION_KUBE_TOKEN
      - PRODUCTION_KEYCLOAK_URL
      - PRODUCTION_KEYCLOAK_PROTOCOL
      - PRODUCTION_KEYCLOAK_REALM
      - PRODUCTION_COP_DATA_API_KEYCLOAK_CLIENT_ID
      - PRODUCTION_COP_DATA_API_LOG_LEVEL
      - PRODUCTION_COP_DATA_API_DB_CONNECTION_STRING
      - PRODUCTION_DB_DATA_COP_OPERATION_SCHEMA
      - PRODUCTION_COP_DATA_API_IMAGE_REPO
      - PRODUCTION_COP_DATA_API_PORT
      - PRODUCTION_NGINX_IMAGE_PROXY_REPO
      - PRODUCTION_NGINX_IMAGE_PROXY_TAG
    commands:
      - export HOSTNAME=$${PRODUCTION_HOSTNAME}
      - export COP_DATA_API_KUBE_NAMESPACE=$${PRODUCTION_COP_DATA_API_KUBE_NAMESPACE}
      - export KUBE_SERVER=$${PRODUCTION_KUBE_SERVER}
      - export KUBE_TOKEN=$${PRODUCTION_KUBE_TOKEN}
      - export KEYCLOAK_URL=$${PRODUCTION_KEYCLOAK_URL}
      - export KEYCLOAK_PROTOCOL=$${PRODUCTION_KEYCLOAK_PROTOCOL}
      - export KEYCLOAK_REALM=$${PRODUCTION_KEYCLOAK_REALM}
      - export COP_DATA_API_KEYCLOAK_CLIENT_ID=$${PRODUCTION_COP_DATA_API_KEYCLOAK_CLIENT_ID}
      - export COP_DATA_API_LOG_LEVEL=$${PRODUCTION_COP_DATA_API_LOG_LEVEL}
      - export COP_DATA_API_DB_CONNECTION_STRING=$${PRODUCTION_DB_CONNECTION_STRING}
      - export DB_DATA_COP_OPERATION_SCHEMA=$${PRODUCTION_DB_DATA_COP_OPERATION_SCHEMA}
      - export COP_DATA_API_PORT=$${PRODUCTION_COP_DATA_API_PORT}
      - export COP_DATA_API_IMAGE_REPO=$${PRODUCTION_COP_DATA_API_IMAGE_REPO}
      - export NGINX_PROXY_IMAGE_REPO=$${PRODUCTION_NGINX_PROXY_IMAGE_REPO}
      - export NGINX_PROXY_IMAGE_TAG=$${PRODUCTION_NGINX_PROXY_IMAGE_TAG}
      - kd --insecure-skip-tls-verify -f kube/deployment.yml -f kube/service.yml -f kube/ingress.yml -f kube/network-policy.yml
    when:
      event: deployment
      environment: production
      branch: master
