---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: operational-data-api
spec:
  replicas: 3
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 33%
      maxSurge: 1
  revisionHistoryLimit: 3
  template:
    metadata:
      labels:
        name: operational-data-api
    spec:
      containers:
      - name: api
        image: {{.COP_DATA_API_IMAGE_REPO}}:{{.DRONE_COMMIT_SHA}}
        imagePullPolicy: Always
        securityContext:
          runAsNonRoot: true
          runAsUser: 1000
        resources:
          requests:
            cpu: 100m
            memory: 200Mi
          limits:
            cpu: 200m
            memory: 500Mi
        livenessProbe:
          exec:
            command:
            - node
            - /src/app/healthcheck.js
          initialDelaySeconds: 30
          periodSeconds: 30
        readinessProbe:
          exec:
            command:
              - node
              - /src/app/healthcheck.js
          initialDelaySeconds: 5
          periodSeconds: 5

        env:
        - name: COP_DATA_API_DB_CONNECTION_STRING
          value: {{.COP_DATA_API_DB_CONNECTION_STRING}}
        - name: COP_DATA_API_LOG_LEVEL
          value: {{.COP_DATA_API_LOG_LEVEL}}
        - name: COP_DATA_API_PORT
          value: "{{.COP_DATA_API_PORT}}"
        - name: COP_DATA_API_SEARCH_SCHEMA
          value: {{.COP_DATA_API_SEARCH_SCHEMA}}
        - name: KEYCLOAK_URL
          value: {{.KEYCLOAK_URL}}
        - name: COP_DATA_API_KEYCLOAK_CLIENT_ID
          value: {{.COP_DATA_API_KEYCLOAK_CLIENT_ID}}
        ports:
          - name: api
            containerPort: "{{.COP_DATA_API_PORT}}"

      - name: proxy
        image: {{.NGINX_PROXY_IMAGE_REPO}}:{{.NGINX_PROXY_IMAGE_TAG}}
        securityContext:
          runAsNonRoot: true
        env:
          - name: PROXY_SERVICE_HOST
            value: 'http://127.0.0.1'
          - name: PROXY_SERVICE_PORT
            value: "{{.COP_DATA_API_PORT}}"
          - name: LOG_FORMAT_NAME
            value: 'json'
          - name: NAXSI_USE_DEFAULT_RULES
            value: 'FALSE'
          - name: ENABLE_UUID_PARAM
            value: 'FALSE'
        ports:
          - name: https
            containerPort: 10443
