---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: operational-data-api
spec:
  replicas: 3
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 33%
      maxSurge: 1
  revisionHistoryLimit: 3
  template:
    metadata:
      labels:
        name: operational-data-api
    spec:
      containers:
      - name: api
        image: "{{.API_COP_IMAGE}}:{{.DRONE_COMMIT_SHA}}"
        imagePullPolicy: Always
        securityContext:
          runAsNonRoot: true
          runAsUser: 1000
        resources:
          requests:
            cpu: 100m
            memory: 200Mi
          limits:
            cpu: 200m
            memory: 500Mi
        livenessProbe:
          exec:
            command:
            - node
            - /src/app/healthcheck.js
          initialDelaySeconds: 30
          periodSeconds: 30
        readinessProbe:
          exec:
            command:
              - node
              - /src/app/healthcheck.js
          initialDelaySeconds: 5
          periodSeconds: 5

        env:
        - name: DB_COP_PROTOCOL
          value: {{.DB_COP_PROTOCOL}}
        - name: DB_COP_PORT
          value: {{.DB_COP_PORT}}
        - name: DB_COP_HOSTNAME
          value: {{.DB_COP_HOSTNAME}}
        - name: DB_COP_OPTIONS
          value: {{.DB_COP_OPTIONS}}
        - name: DB_COP_OPERATION_DBNAME
          value: {{.DB_COP_OPERATION_DBNAME}}
        - name: DB_COP_OPERATION_SCHEMA
          value: {{.DB_COP_OPERATION_SCHEMA}}
        - name: DB_COP_OPERATION_AUTHENTICATOR_USERNAME
          value: {{.DB_COP_OPERATION_AUTHENTICATOR_USERNAME}}
        - name: DB_COP_OPERATION_AUTHENTICATOR_PASSWORD
          value: {{.DB_COP_OPERATION_AUTHENTICATOR_PASSWORD}}
        - name: API_COP_LOG_LEVEL
          value: {{.API_COP_LOG_LEVEL}}
        - name: API_COP_PORT
          value: "{{.API_COP_PORT}}"
        - name: API_COP_SEARCH_SCHEMA
          value: {{.API_COP_SEARCH_SCHEMA}}
        - name: KEYCLOAK_URL
          value: {{.KEYCLOAK_URL}}
        - name: KEYCLOAK_PROTOCOL
          value: {{.KEYCLOAK_PROTOCOL}}
        - name: KEYCLOAK_REALM
          value: {{.KEYCLOAK_REALM}}
        - name: API_COP_KEYCLOAK_CLIENT_ID
          value: {{.API_COP_KEYCLOAK_CLIENT_ID}}
        ports:
          - name: api
            containerPort: "{{.API_COP_PORT}}"
      - name: proxy
        image: "{{.NGINX_IMAGE}}:{{.NGINX_TAG}}"
        securityContext:
          runAsNonRoot: true
        env:
          - name: PROXY_SERVICE_HOST
            value: 'http://127.0.0.1'
          - name: PROXY_SERVICE_PORT
            value: "{{.API_COP_PORT}}"
          - name: LOG_FORMAT_NAME
            value: 'json'
          - name: NAXSI_USE_DEFAULT_RULES
            value: 'FALSE'
          - name: ENABLE_UUID_PARAM
            value: 'FALSE'
        ports:
          - name: https
            containerPort: 10443
