---
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: operational-data-api-ingress
  labels:
    stable.k8s.psg.io/kcm.class: default
  annotations:
    kubernetes.io/ingress.class: "nginx-external"
    ingress.kubernetes.io/force-ssl-redirect: "true"
    ingress.kubernetes.io/backend-protocol: "HTTPS"
    stable.k8s.psg.io/kcm.provider: http
spec:
  rules:
  - host: {{.API_COP_URL}}
    http:
      paths:
      - backend:
          serviceName: operational-data-api-service
          servicePort: 10443
        path: /
  tls:
  - hosts:
    - {{.API_COP_URL}}
    secretName: operational-data-api-tls
